<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */
$_code=$this->getMethodCode();
?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
         <li>
            <a id="more_info_<?php echo $_code; ?>" href="https://developerredecard.github.io/Checkout-Redecard/" target="_blank"><?php echo __('More information about Checkout Redecard') ?></a>
        </li>
    </ul>
</fieldset>
<div>
</div>