<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */

/*dump($this->getData());
dump(get_class_methods(get_class($this)));
dump(get_class_vars(get_class($this)));*/

?>

<!-- <?php echo get_class($this) ?> -->

<script type="text/javascript">
console.log('<?php echo get_class($this) ?>');
</script>

<?php if ($this->isCurrentMethod()): ?>

	<div class="redecard-checkout-onepage-success">

		<?php if ($this->isBoletoPayment()): ?>
		<div class="payment-url">
		    <?php echo Mage::helper('mozg_redecard')->__('<a href="%s">Click here to download the Boleto payment PDF</a>', $this->getPaymentUrl()) ?>
		</div>
		<?php endif; ?>

		<?php if ($this->isEletronicTransferPayment()): ?>
		<div class="payment-url">
		    <?php echo Mage::helper('mozg_redecard')->__('<a href="%s">Click here to process the EletronicTransfer payment</a>', $this->getPaymentUrl()) ?>
		</div>
		<?php endif; ?>

		<?php /* ?>

		<div id="ajax-mozg-success" style="border:1px solid red; display:none;">Aguarde o envio da notificação</div>

		<script type="text/javascript">

		pre.show('Processando...');

		</script>

		<script type="text/javascript">

			var url = '<?php echo $this->getPaymentNotificationUrl(); ?>';

			var element = 'ajax-mozg-success';

			var req = new Ajax.Request( url, {
			    method: 'get',
			    asynchronous: false,
			    onLoading: function(transport) {
			    	console.log('onLoading');
			    },
			    onCreate: function(transport) {
			    	console.log('onCreate');	        
			    },
			    onComplete: function(transport) {
			    	console.log('onComplete');
			        
			        //console.dir(transport);

			        console.log('pre');

			        console.log(pre);

			        pre.hide();

			        $(element).innerHTML = transport.responseText;
			        
			    }
			});

			console.log(req);

		</script>

		<?php */ ?>

	</div>

<?php endif; ?>

<!-- / <?php echo get_class($this) ?> -->